name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - statsmodels
  - torchaudio
  - torchvision